In [1]:
import pandas as pd
import numpy as np
import datetime
import shutil
import os
import boto3
import io
import glob
import pathlib

In [2]:
ls

 Volume in drive D is New Volume
 Volume Serial Number is 78F4-D7DB

 Directory of D:\BA New Project

08/30/2024  11:20 AM    <DIR>          .
07/22/2024  03:33 PM    <DIR>          .ipynb_checkpoints
08/06/2024  03:21 PM           168,389 asdf.csv
06/17/2024  12:01 PM           768,669 D_0_RAD_12247_data_2024-06-17.xlsx
06/18/2024  11:03 AM           684,276 D_0_RAD_12247_data_2024-06-18.xlsx
07/19/2024  03:17 PM           954,914 D_0_RAD_12247_data_2024-07-19.xlsx
08/29/2024  11:04 AM           178,162 D0 RAD_12247.ipynb
08/02/2024  11:01 AM         1,360,663 FK_Escalation24hrs_01Aug2024_11AM.xlsx
07/02/2024  11:00 AM           787,379 FK_Escalation24hrs_01Jul2024_11AM.xlsx
08/03/2024  11:00 AM         1,171,467 FK_Escalation24hrs_02Aug2024_11AM.xlsx
07/03/2024  11:00 AM           759,804 FK_Escalation24hrs_02Jul2024_11AM.xlsx
07/04/2024  11:21 AM           740,544 FK_Escalation24hrs_03Jul2024_11AM.xlsx
08/05/2024  11:03 AM           880,918 FK_Escalation24hrs_04Aug2024_11AM.xlsx
07/05/2024  11:00 AM           695,188 FK_Escalation24hrs_04Jul2024_11AM.xlsx
08/06/2024  11:01 AM         1,074,645 FK_Escalation24hrs_05Aug2024_11AM.xlsx
07/06/2024  11:00 AM           867,216 FK_Escalation24hrs_05Jul2024_11AM.xlsx
08/08/2024  11:01 AM         1,003,344 FK_Escalation24hrs_07Aug2024_11AM.xlsx
07/08/2024  11:00 AM           674,905 FK_Escalation24hrs_07Jul2024_11AM.xlsx
08/09/2024  11:27 AM           969,991 FK_Escalation24hrs_08Aug2024_11AM.xlsx
07/09/2024  11:00 AM           884,932 FK_Escalation24hrs_08Jul2024_11AM.xlsx
07/10/2024  11:00 AM           926,578 FK_Escalation24hrs_09Jul2024_11AM.xlsx
07/11/2024  11:00 AM         1,077,938 FK_Escalation24hrs_10Jul2024_11AM.xlsx
08/12/2024  11:01 AM           989,031 FK_Escalation24hrs_11Aug2024_11AM.xlsx
07/12/2024  11:01 AM           929,134 FK_Escalation24hrs_11Jul2024_11AM.xlsx
08/13/2024  11:01 AM           941,315 FK_Escalation24hrs_12Aug2024_11AM.xlsx
07/13/2024  11:01 AM           934,875 FK_Escalation24hrs_12Jul2024_11AM.xlsx
08/14/2024  12:03 PM           974,235 FK_Escalation24hrs_13Aug2024_12PM.xlsx
06/14/2024  11:54 AM         1,300,633 FK_Escalation24hrs_13Jun2024_11AM.xlsx
07/15/2024  11:01 AM           877,777 FK_Escalation24hrs_14Jul2024_11AM.xlsx
08/16/2024  11:00 AM         1,189,220 FK_Escalation24hrs_15Aug2024_11AM.xlsx
08/17/2024  11:01 AM         1,359,959 FK_Escalation24hrs_16Aug2024_11AM.xlsx
06/17/2024  11:00 AM           793,831 FK_Escalation24hrs_16Jun2024_11AM.xlsx
07/18/2024  11:00 AM           969,490 FK_Escalation24hrs_17Jul2024_11AM.xlsx
06/18/2024  03:00 PM           720,957 FK_Escalation24hrs_17Jun2024_03PM.xlsx
06/18/2024  11:01 AM           719,563 FK_Escalation24hrs_17Jun2024_11AM.xlsx
07/19/2024  03:01 PM           944,619 FK_Escalation24hrs_18Jul2024_03PM.xlsx
06/19/2024  03:00 PM         1,224,585 FK_Escalation24hrs_18Jun2024_03PM.xlsx
06/19/2024  11:33 AM         1,223,671 FK_Escalation24hrs_18Jun2024_11AM.xlsx
08/20/2024  11:01 AM         1,355,887 FK_Escalation24hrs_19Aug2024_11AM.xlsx
07/20/2024  11:01 AM         1,034,751 FK_Escalation24hrs_19Jul2024_11AM.xlsx
06/20/2024  11:01 AM         1,109,382 FK_Escalation24hrs_19Jun2024_11AM.xlsx
08/21/2024  11:01 AM         1,310,077 FK_Escalation24hrs_20Aug2024_11AM.xlsx
06/21/2024  11:43 AM         1,068,262 FK_Escalation24hrs_20Jun2024_11AM.xlsx
08/22/2024  11:01 AM         1,305,552 FK_Escalation24hrs_21Aug2024_11AM.xlsx
07/22/2024  11:00 AM           799,673 FK_Escalation24hrs_21Jul2024_11AM.xlsx
06/22/2024  05:01 PM           974,666 FK_Escalation24hrs_21Jun2024_05PM.xlsx
06/22/2024  11:44 AM           973,662 FK_Escalation24hrs_21Jun2024_11AM.xlsx
08/23/2024  11:01 AM         1,208,609 FK_Escalation24hrs_22Aug2024_11AM.xlsx
07/23/2024  11:00 AM         1,081,983 FK_Escalation24hrs_22Jul2024_11AM.xlsx
08/24/2024  11:01 AM         1,073,287 FK_Escalation24hrs_23Aug2024_11AM.xlsx
07/24/2024  11:01 AM         1,021,435 FK_Escalation24hrs_23Jul2024_11AM.xlsx
07/25/2024  11:01 AM           958,448 FK_Escalation24hrs_24Jul2024_11AM.xlsx
06/25/2024  11:00 AM           632,250 FK_Escalation24hrs_24Jun2024_11AM.xlsx
07/26/2024  11:01 AM         1,098,652 FK_Escalation24hrs_25Jul2024_11AM.xlsx
06/26/2024  03:00 PM           789,881 FK_Escalation24hrs_25Jun2024_03PM.xlsx
06/26/2024  11:25 AM           788,803 FK_Escalation24hrs_25Jun2024_11AM.xlsx
08/27/2024  11:01 AM           884,047 FK_Escalation24hrs_26Aug2024_11AM.xlsx
06/27/2024  11:00 AM           896,011 FK_Escalation24hrs_26Jun2024_11AM.xlsx
08/28/2024  05:14 PM           806,646 FK_Escalation24hrs_27Aug2024_05PM.xlsx
08/28/2024  12:33 PM           805,647 FK_Escalation24hrs_27Aug2024_12PM.xlsx
06/28/2024  11:43 AM           884,078 FK_Escalation24hrs_27Jun2024_11AM.xlsx
08/29/2024  11:01 AM           878,791 FK_Escalation24hrs_28Aug2024_11AM.xlsx
07/29/2024  11:00 AM         1,132,118 FK_Escalation24hrs_28Jul2024_11AM.xlsx
08/30/2024  11:01 AM           961,828 FK_Escalation24hrs_29Aug2024_11AM.xlsx
07/30/2024  11:01 AM         1,419,710 FK_Escalation24hrs_29Jul2024_11AM.xlsx
07/31/2024  11:01 AM         1,447,169 FK_Escalation24hrs_30Jul2024_11AM.xlsx
07/01/2024  11:49 AM           744,089 FK_Escalation24hrs_30Jun2024_11AM.xlsx
07/31/2024  04:32 PM    <DIR>          Performance weekly
08/13/2024  02:03 PM           566,383 RAD_12247_Report 2.ipynb
06/13/2024  11:00 AM        13,313,602 RAD_ESC_Data_12247_2024Jun12.xlsx
06/19/2024  10:52 AM             5,771 Untitled.ipynb
06/19/2024  04:09 PM               726 Untitled1.ipynb
06/20/2024  02:26 PM         6,553,349 Untitled2.ipynb
06/20/2024  03:00 PM            40,062 Untitled3.ipynb
06/21/2024  11:17 AM            23,527 Untitled4.ipynb
06/21/2024  10:05 PM            52,714 Untitled5.ipynb
06/26/2024  10:48 AM            10,033 Untitled6.ipynb
07/03/2024  12:25 PM            41,200 Untitled7.ipynb
07/22/2024  04:33 PM            22,344 Untitled8.ipynb
08/07/2024  10:27 AM    <DIR>          Whats app
              76 File(s)     82,797,922 bytes
               4 Dir(s)  52,343,988,224 bytes free

In [3]:
os.chdir(r"D:\\BA New Project")

In [4]:
os.getcwd()

'D:\\BA New Project'

In [5]:
#

In [6]:
df=pd.read_excel("FK_Escalation24hrs_29Aug2024_11AM.xlsx",sheet_name="Base_Data_24hrs")
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Status_New,Last_OFD_Date,Excluded Attempts,Open_Close,Destination_SC,Destination_Pincode,Destination_City,Destination_State,Vendor,Embargo Status
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Attempted customer dependency,2024-08-12 12:52:02,1.0,Open,PNA,411047.0,PUNE,Maharashtra,Address Unlocatable/Phone Not Reachable,No Action
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,>=3 attempts,2024-08-29 10:34:13,3.0,Open,VNL,600048.0,VANDALUR,Tamil Nadu,Customer Refused Delivery at Doorstep,No Action

In [7]:
df['F/R'].value_counts(dropna = False)

F/R
FWD    6894
Name: count, dtype: int64

In [8]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Pickup_Date', 'Status_New',
       'Last_OFD_Date', 'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status'],
      dtype='object')

In [9]:
df["Report_Date"]=datetime.datetime.today().strftime("%Y-%m-%d")
df["Shipper_Rad_Date"]=df["Report_Date"]

In [10]:
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Excluded Attempts,Open_Close,Destination_SC,Destination_Pincode,Destination_City,Destination_State,Vendor,Embargo Status,Report_Date,Shipper_Rad_Date
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,1.0,Open,PNA,411047.0,PUNE,Maharashtra,Address Unlocatable/Phone Not Reachable,No Action,2024-08-30,2024-08-30
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,3.0,Open,VNL,600048.0,VANDALUR,Tamil Nadu,Customer Refused Delivery at Doorstep,No Action,2024-08-30,2024-08-30

In [11]:
# mm=[]
# for i in df["task_tracking_id"]:
#     if i in x:
#         mm.append(i)
# len(mm)

In [12]:
# m=[]
# for i in range(len(df["task_tracking_id"])):
#     if df["task_tracking_id"][i] in x:
#         m.append(df["task_tracking_id"][i])
#     else:
#         m.append(0)

In [13]:
df["Airwaybill_No"]=df["task_tracking_id"]

In [14]:
df

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Open_Close,Destination_SC,Destination_Pincode,Destination_City,Destination_State,Vendor,Embargo Status,Report_Date,Shipper_Rad_Date,Airwaybill_No
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Open,PNA,411047.0,PUNE,Maharashtra,Address Unlocatable/Phone Not Reachable,No Action,2024-08-30,2024-08-30,10385286700
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Open,VNL,600048.0,VANDALUR,Tamil Nadu,Customer Refused Delivery at Doorstep,No Action,2024-08-30,2024-08-30,10382037441
2,Flipkart,FWD,IN24081218501898024516ITaiyNEb,IN24081218501898024516,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384264806,2024-08-14 20:06:43,15,...,Open,COR,312622.0,CHITTOR GARH,Rajasthan,Address Unlocatable/Phone Not Reachable,No Action,2024-08-30,2024-08-30,10384264806
3,Flipkart,FWD,IN24081218523556393635ITqL86AL,IN24081218523556393635,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3305950522,2024-08-14 20:07:42,15,...,Open,PPK,517130.0,PUTHALAPATTU,Andhra Pradesh,Not Available At Given Address,No Action,2024-08-30,2024-08-30,3305950522
4,Flipkart,FWD,IN24081220312236798464ITUvixX9,IN24081220312236798464,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384193760,2024-08-14 21:21:37,15,...,Open,SXF,191121.0,SRINAGAR,Jammu And Kashmir,Out Of Station,No Action,2024-08-30,2024-08-30,10384193760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6889,Myntra,FWD,IN24082817344596547490ITDKL5NC,IN24082817344596547490ITDKL5NC,Disputed delivery,Disputing delivery attempt,Open,10398779472,2024-08-29 00:00:00,0,...,Close,BRY,243202.0,BAREILLY,Uttar Pradesh,Delivered,No Action,2024-08-30,2024-08-30,10398779472
6890,Myntra,FWD,IN24082817372541324346ITswCT6E,IN24082817372541324346ITswCT6E,Disputed delivery,Disputing delivery attempt,Open,3313314325,2024-08-29 00:00:00,0,...,Close,DYV,110093.0,DELHI,Delhi,Delivered,No Action,2024-08-30,2024-08-30,3313314325
6891,Myntra,FWD,IN24082817403971867352ITRI7csT,IN24082817403971867352ITRI7csT,Disputed delivery,Disputing delivery attempt,Open,3313000970,2024-08-29 00:00:00,0,...,Open,ABU,307501.0,ABU ROAD,Rajasthan,Address Unlocatable/Phone Not Reachable,No Action,2024-08-30,2024-08-30,3313000970
6892,Myntra,FWD,IN24082817472788507266ITXOaRca,IN24082817472788507266ITXOaRca,Order Status,Shipped To Delivered,Open,10396403676,2024-08-29 00:00:00,0,...,Close,MDHU,123106.0,BHIWADI,Haryana,Undelivered,No Action,2024-08-30,2024-08-30,10396403676
6893,Myntra,FWD,IN24082817481320450104ITZp0UcK,IN24082817481320450104ITZp0UcK,Order Status,Incorrectly Marked Delivered,Open,10398378907,2024-08-29 00:00:00,0,...,Close,BTT,344025.0,BALOTRA,Rajasthan,Delivered,No Action,2024-08-30,2024-08-30,10398378907

In [15]:
df=df[df["Airwaybill_No"]!=0]
len(df)

6894

In [16]:
def value_interpreter(number,limit):
    import math
    final_val = math.ceil(number/limit)
    list_values = [0]
    for i in range(final_val):
        value_append = (i+1)*limit
        if value_append<number:
            list_values.append((i+1)*limit)
        else:
            list_values.append(number)
    return final_val,list_values

In [17]:
def query_run_with_batch_size(host,port,user,password,db_name,batch_size,query_start,query_end,awb_to_find):
    """
    Either pass as List or as Dataframe for awb_to_find
    """
    #import pandas as pd
    import pymysql
    import warnings
    warnings.filterwarnings("ignore")
    #looping over
    data_list_1 = []

    if type(awb_to_find) != pd.core.frame.DataFrame:
        y = pd.DataFrame({'val_to_find':awb_to_find})
    else:
        y = awb_to_find
        
    a,b = value_interpreter(len(y[y.columns[0]]),batch_size)
    for i,j in enumerate(b):
        if ((i+1)==len(b)):
            pass
        else:
            print('Working Range : ',str(j),'-',str(b[i+1]))

            query_data = query_start+ (',').join(y[y.columns[0]][j:b[i+1]].apply(lambda x:str(int(x)))) +query_end
            conn = pymysql.connect(host= host , port=port , user=user , passwd=password, db=db_name)
            print(conn)
            dt1 = datetime.datetime.now()
            temp_data = pd.read_sql(query_data,conn)
            dt2 = datetime.datetime.now()
            print('time takent to execute and fetch the query: ' ,dt2-dt1)
            print(temp_data.shape)
            print('Saving_data of Batch: %d of Total Batch %d\n'%(i+1,len(b)-1))
            data_list_1.append(temp_data)
    
    data = pd.concat(data_list_1)
    print(data.shape)
    return data

In [18]:
def plain_query(host,port,user,password,db_name,query_data):
    import pymysql
    
    try:
        conn = pymysql.connect(host= host , port=port , user=user , passwd=password, db=db_name)
        d1 = datetime.datetime.now()
        temp_data = pd.read_sql(query_data,conn)
        d2 = datetime.datetime.now()
        print('time taken to execute and fetch : ',d2-d1)
        conn.close
    except:
        conn = pymysql.connect(host= host , port=port , user=user , passwd=password, db=db_name)
        d1 = datetime.datetime.now()
        temp_data = pd.read_sql(query_data,conn)
        d2 = datetime.datetime.now()
        print('time taken to execute and fetch : ',d2-d1)
        conn.close

    return temp_data

In [19]:
######### Scadi_shipments #####################
host='3.7.215.20'
port=3306
user='de_ss_comon'
password='Con@%^&(*657'
db_name= 'Scadi_Shipments'
batch_size= 5000

In [20]:
query_start = """
        select
        s.airwaybill_number as 'Airwaybill_No',
        s.inscan_date as 'Pickup_Date',
        case when s.product_type_id = 4 then 'RVP' else mpt.type_category end as 'Product_Type',
        #s.id as 'Shipment_id',
        org.center_code as 'Origin_DC' ,
        curr.center_code as 'Current_SC',
        type.type_code as 'SC_Type',
        dest.center_code as 'Dest_DC',
        mdmc.city_name as 'Dest_City',
        mdms.state_code as 'Dest_State',
        mdmr.region_name as 'Dest_Region',
        s.updated_on as 'Latest_shipment_updation',
        datediff(current_date(),date(s.updated_on)) as 'Aging',
        s.current_status_id as 'Current_Status_ID',
        mss.status_name as 'Current_Status',
        s.current_reason_id as 'Current_Status_Reason_ID',
        mssr.reason_code as 'Reason_Code',
        mssr.reason_name as 'Current_Status_Reason',
        s.declared_value as 'Declared_Value',

        # case when (s.product_type_id in (1,2,3) and  (s.is_cod = 'Y')) then 'FWD-COD'
        #      when (s.product_type_id in (1,2,3) and  (s.is_cod != 'Y')) then 'FWD-PPD'
        #      when s.product_type_id = 4 then 'RVP' 
        #      when s.product_type_id = 7 then 'RTS' 
        # else Null end as 'AWB_Type',

                
        (select sfh.fact_date   
            from shipment_fact_history sfh 
            where sfh.shipment_id = s.id and sfh.fact_id in (8) order by sfh.fact_date desc limit 1 ) as 'Bulk_Order',

            
	  case 
	       when s.current_status_id = 21 then 'Delivered' 
	       when s.current_status_id = 22 then 'Returned'
	   else 'Undelivered' end as 'Closure_Status',

    (select h.scan_date from shipment_history h where h.shipment_id = s.id order by h.id desc  limit 1 ) as 'latest_status_update',
    (select h.scan_date from shipment_history h where h.shipment_id = s.id and h.status_id= 29 order by h.id  desc  limit 1 ) as 'latest_attempt',
	(select (max(sh.updated_on)) from shipment_instructions_history sh where s.id = sh.shipment_id and sh.instruction_id =21 and sh.status = 'O') as 'RTO_Lock',
	(select (max(sh.updated_on)) from shipment_instructions_history sh where s.id = sh.shipment_id and sh.instruction_id =22 and sh.status = 'O') as 'OFD_Lock'

        from shipments s #force index (IX_shipments_inscan_date)
        left join mdm_service_centers org on org.id = s.original_pickup_sc_id
        left join mdm_service_centers dest on dest.id = s.dest_sc_id
        left join mdm_service_centers curr on curr.id = s.current_sc_id 
        left join mdm_service_center_types type on type.id=curr.type_id
        left join mdm_shipment_status mss on mss.id = s.current_status_id
        left join mdm_shipment_status_reasons mssr on mssr.id=s.current_reason_id
        left join mdm_product_types mpt on mpt.id = s.product_type_id

        left join mdm_service_locations msl on msl.id = dest.location_id
        left join mdm_cities mdmc on mdmc.id = msl.city_id
        left join mdm_states mdms on mdms.id = mdmc.state_id
        left join mdm_regions mdmr on mdmr.id = mdms.region_id

        where 1=1
        and s.airwaybill_number in (
"""
query_end = """
)
"""

In [21]:
awb_to_find = df[['Airwaybill_No']].copy()
print(awb_to_find.shape)
awb_to_find.drop_duplicates(subset = ['Airwaybill_No'], ignore_index=True, inplace = True)
print(awb_to_find.shape)

(6894, 1)
(6881, 1)

In [22]:
df1 = query_run_with_batch_size(host,port,user,password,db_name,batch_size,query_start,query_end,awb_to_find)
print(df1.shape)
df1.head()

Working Range :  0 - 5000
<pymysql.connections.Connection object at 0x0000026360F83F50>
time takent to execute and fetch the query:  0:00:02.000957
(4980, 24)
Saving_data of Batch: 1 of Total Batch 2

Working Range :  5000 - 6881
<pymysql.connections.Connection object at 0x000002636162B890>
time takent to execute and fetch the query:  0:00:00.913938
(1845, 24)
Saving_data of Batch: 2 of Total Batch 2

(6825, 24)
(6825, 24)

,Airwaybill_No,Pickup_Date,Product_Type,Origin_DC,Current_SC,SC_Type,Dest_DC,Dest_City,Dest_State,Dest_Region,...,Current_Status_Reason_ID,Reason_Code,Current_Status_Reason,Declared_Value,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock
0,610898877,2024-08-20 18:38:53,FWD,MRUP,MRUP,DC,KJG,KENDUJHARGARH,OR,East,...,NaN,None,None,2395.0,NaT,Undelivered,2024-08-29 08:03:36,NaT,NaT,NaT
1,610898936,2024-08-20 18:38:47,FWD,MRUP,MRUP,DC,EGM,ETURNAGARAM,TS,South,...,NaN,None,None,2162.0,NaT,Undelivered,2024-08-29 08:03:16,NaT,NaT,NaT
2,610899049,2024-08-21 12:37:12,FWD,DOR,PYN,DC,PYN,PUNE,MH,West,...,NaN,None,None,1772.0,NaT,Delivered,2024-08-29 13:28:48,2024-08-29 11:39:52,NaT,NaT
3,610899075,2024-08-21 12:37:32,FWD,FAB,MSI,DC,MSI,MULSHI,MH,West,...,NaN,None,None,1272.0,NaT,Delivered,2024-08-30 11:08:25,2024-08-30 10:28:59,NaT,NaT
4,610899087,2024-08-22 12:51:27,FWD,DOR,CCQ,DC,CCQ,KOLKATA,WB,East,...,NaN,None,None,1291.0,NaT,Delivered,2024-08-28 19:15:26,2024-08-28 10:18:11,NaT,NaT

In [23]:
df1['Product_Type'].value_counts(dropna = False)

Product_Type
FWD    6825
Name: count, dtype: int64

In [24]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Pickup_Date', 'Status_New',
       'Last_OFD_Date', 'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status', 'Report_Date', 'Shipper_Rad_Date',
       'Airwaybill_No'],
      dtype='object')

In [25]:
df=df.drop("Pickup_Date",axis=1)
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Open_Close,Destination_SC,Destination_Pincode,Destination_City,Destination_State,Vendor,Embargo Status,Report_Date,Shipper_Rad_Date,Airwaybill_No
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Open,PNA,411047.0,PUNE,Maharashtra,Address Unlocatable/Phone Not Reachable,No Action,2024-08-30,2024-08-30,10385286700
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Open,VNL,600048.0,VANDALUR,Tamil Nadu,Customer Refused Delivery at Doorstep,No Action,2024-08-30,2024-08-30,10382037441

In [26]:
df1.columns

Index(['Airwaybill_No', 'Pickup_Date', 'Product_Type', 'Origin_DC',
       'Current_SC', 'SC_Type', 'Dest_DC', 'Dest_City', 'Dest_State',
       'Dest_Region', 'Latest_shipment_updation', 'Aging', 'Current_Status_ID',
       'Current_Status', 'Current_Status_Reason_ID', 'Reason_Code',
       'Current_Status_Reason', 'Declared_Value', 'Bulk_Order',
       'Closure_Status', 'latest_status_update', 'latest_attempt', 'RTO_Lock',
       'OFD_Lock'],
      dtype='object')

In [27]:
df1 = df1[['Airwaybill_No','Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC', 'Latest_shipment_updation', 'Current_Status_ID','Current_Status', 
           'Current_Status_Reason_ID', 'Reason_Code','Current_Status_Reason', 'Bulk_Order','Closure_Status', 'latest_status_update',
           'latest_attempt','RTO_Lock','OFD_Lock']].copy()

In [28]:
print(df.shape)

df = df.merge(df1, how = 'left', on = 'Airwaybill_No')

print(df.shape)

(6894, 27)
(6894, 43)

In [29]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Status_New', 'Last_OFD_Date',
       'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status', 'Report_Date', 'Shipper_Rad_Date',
       'Airwaybill_No', 'Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC',
       'Latest_shipment_updation', 'Current_Status_ID', 'Current_Status',
       'Current_Status_Reason_ID', 'Reason_Code', 'Current_Status_Reason',
       'Bulk_Order', 'Closure_Status', 'latest_status_update',
       'latest_attempt', 'RTO_Lock', 'OFD_Lock'],
      dtype='object')

In [30]:
df.head()

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Current_Status,Current_Status_Reason_ID,Reason_Code,Current_Status_Reason,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Undelivered,63.0,RSN_10_120,Address Unlocatable/Phone Not Reachable,NaT,Undelivered,2024-08-12 15:38:53,2024-08-12 12:52:02,NaT,NaT
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Undelivered,106.0,RSN_40_240,Customer Refused Delivery at Doorstep,NaT,Undelivered,2024-08-29 13:22:59,2024-08-29 10:34:13,NaT,NaT
2,Flipkart,FWD,IN24081218501898024516ITaiyNEb,IN24081218501898024516,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384264806,2024-08-14 20:06:43,15,...,Undelivered,63.0,RSN_10_120,Address Unlocatable/Phone Not Reachable,2024-08-16 07:52:57,Undelivered,2024-08-28 12:41:36,2024-08-28 11:22:21,NaT,2024-08-30 00:37:40
3,Flipkart,FWD,IN24081218523556393635ITqL86AL,IN24081218523556393635,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3305950522,2024-08-14 20:07:42,15,...,Undelivered,9.0,RSN_10_40,Not Available At Given Address,NaT,Undelivered,2024-08-20 17:36:09,2024-08-20 11:44:06,NaT,2024-08-27 00:28:36
4,Flipkart,FWD,IN24081220312236798464ITUvixX9,IN24081220312236798464,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384193760,2024-08-14 21:21:37,15,...,Undelivered,10.0,RSN_10_50,Out Of Station,NaT,Undelivered,2024-08-26 14:16:26,2024-08-26 11:00:04,NaT,NaT

In [31]:
df['At_DC'] = np.where(df['Dest_DC'] == df['Current_SC'],'Yes','No')
df['At_DC'].value_counts(dropna = False)

At_DC
Yes    5375
No     1519
Name: count, dtype: int64

In [32]:
df['Closure_Status'].value_counts(dropna = False)

Closure_Status
Undelivered    5041
Delivered      1168
Returned        629
NaN              56
Name: count, dtype: int64

In [33]:
df['At_DC'] = np.where(df['Closure_Status'].isin(['Delivered','Returned']),'Yes',df['At_DC'] )
df['At_DC'].value_counts(dropna = False)

At_DC
Yes    5404
No     1490
Name: count, dtype: int64

In [34]:
exlcude_codes = [25,31,35,37,43,44,45,46,48,52,81,82,83,84,85,86,87,88,96,97,98,99,100,101]

In [35]:
df['Exclude_Reasons'] = np.where(df['Current_Status_Reason_ID'].isin(exlcude_codes),'Excluded','Include')
df['Exclude_Reasons'].value_counts(dropna = False)

Exclude_Reasons
Include     6844
Excluded      50
Name: count, dtype: int64

In [36]:
df['Bulk_Order'].value_counts(dropna = False)

Bulk_Order
NaT                    6795
2024-08-26 19:54:44       3
2024-08-28 20:11:12       3
2024-08-26 19:55:25       3
2024-08-27 20:03:04       3
                       ...
2024-08-16 07:52:57       1
2024-08-27 20:02:59       1
2024-08-27 20:03:00       1
2024-08-29 17:52:15       1
2024-08-21 20:23:32       1
Name: count, Length: 75, dtype: int64

In [37]:
df.loc[df['Bulk_Order'].isnull()].head()

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Reason_Code,Current_Status_Reason,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock,At_DC,Exclude_Reasons
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,RSN_10_120,Address Unlocatable/Phone Not Reachable,NaT,Undelivered,2024-08-12 15:38:53,2024-08-12 12:52:02,NaT,NaT,Yes,Include
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,RSN_40_240,Customer Refused Delivery at Doorstep,NaT,Undelivered,2024-08-29 13:22:59,2024-08-29 10:34:13,NaT,NaT,Yes,Include
3,Flipkart,FWD,IN24081218523556393635ITqL86AL,IN24081218523556393635,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3305950522,2024-08-14 20:07:42,15,...,RSN_10_40,Not Available At Given Address,NaT,Undelivered,2024-08-20 17:36:09,2024-08-20 11:44:06,NaT,2024-08-27 00:28:36,Yes,Include
4,Flipkart,FWD,IN24081220312236798464ITUvixX9,IN24081220312236798464,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384193760,2024-08-14 21:21:37,15,...,RSN_10_50,Out Of Station,NaT,Undelivered,2024-08-26 14:16:26,2024-08-26 11:00:04,NaT,NaT,Yes,Include
5,Flipkart,FWD,IN24081115004371735308ITjdzE8o,IN24081115004371735308,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382575739,2024-08-15 02:35:36,14,...,None,None,NaT,Returned,2024-08-30 07:07:53,2024-08-08 09:55:52,NaT,2024-08-08 17:00:33,Yes,Include

In [38]:
df['Exclude_Reasons'] = np.where(~df['Bulk_Order'].isnull(), 'Excluded',df['Exclude_Reasons'])
df['Exclude_Reasons'].value_counts(dropna = False)

Exclude_Reasons
Include     6745
Excluded     149
Name: count, dtype: int64

In [39]:
df['Exclude_Reasons'] = np.where(df['Closure_Status'] == 'Delivered', 'Include',df['Exclude_Reasons'])
df['Exclude_Reasons'].value_counts(dropna = False)

Exclude_Reasons
Include     6751
Excluded     143
Name: count, dtype: int64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Source                    6894 non-null   object
 1   F/R                       6894 non-null   object
 2   taskIncidentId            6894 non-null   object
 3   csIncident                6894 non-null   object
 4   Category 1                6894 non-null   object
 5   Category 2                6894 non-null   object
 6   taskStatus                6894 non-null   object
 7   task_tracking_id          6894 non-null   int64
 8   createdOn                 6894 non-null   datetime64[ns]
 9   Incident aging            6894 non-null   int64
 10  Incident aging Bucket     6894 non-null   object
 11  partnerCourierPartner     6894 non-null   object
 12  incidentPriority          6894 non-null   object
 13  vendor_collated           6894 non-null   object
 14  Status_New                6894 non-null   object
 15  Last_OFD_Date             4742 non-null   datetime64[ns]
 16  Excluded Attempts         6746 non-null   float64
 17  Open_Close                6894 non-null   object
 18  Destination_SC            6838 non-null   object
 19  Destination_Pincode       6838 non-null   float64
 20  Destination_City          6838 non-null   object
 21  Destination_State         6838 non-null   object
 22  Vendor                    6836 non-null   object
 23  Embargo Status            6894 non-null   object
 24  Report_Date               6894 non-null   object
 25  Shipper_Rad_Date          6894 non-null   object
 26  Airwaybill_No             6894 non-null   int64
 27  Pickup_Date               6778 non-null   datetime64[ns]
 28  Product_Type              6838 non-null   object
 29  Dest_DC                   6838 non-null   object
 30  Current_SC                6838 non-null   object
 31  Latest_shipment_updation  6838 non-null   datetime64[ns]
 32  Current_Status_ID         6838 non-null   float64
 33  Current_Status            6838 non-null   object
 34  Current_Status_Reason_ID  3282 non-null   float64
 35  Reason_Code               3282 non-null   object
 36  Current_Status_Reason     3282 non-null   object
 37  Bulk_Order                99 non-null     datetime64[ns]
 38  Closure_Status            6838 non-null   object
 39  latest_status_update      6838 non-null   datetime64[ns]
 40  latest_attempt            4931 non-null   datetime64[ns]
 41  RTO_Lock                  863 non-null    datetime64[ns]
 42  OFD_Lock                  283 non-null    datetime64[ns]
 43  At_DC                     6894 non-null   object
 44  Exclude_Reasons           6894 non-null   object
dtypes: datetime64[ns](9), float64(4), int64(3), object(29)
memory usage: 2.4+ MB

In [41]:
df['latest_status_update1'] = pd.to_datetime(df['latest_status_update'],errors='coerce').dt.date
df.head()

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Current_Status_Reason,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock,At_DC,Exclude_Reasons,latest_status_update1
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Address Unlocatable/Phone Not Reachable,NaT,Undelivered,2024-08-12 15:38:53,2024-08-12 12:52:02,NaT,NaT,Yes,Include,2024-08-12
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Customer Refused Delivery at Doorstep,NaT,Undelivered,2024-08-29 13:22:59,2024-08-29 10:34:13,NaT,NaT,Yes,Include,2024-08-29
2,Flipkart,FWD,IN24081218501898024516ITaiyNEb,IN24081218501898024516,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384264806,2024-08-14 20:06:43,15,...,Address Unlocatable/Phone Not Reachable,2024-08-16 07:52:57,Undelivered,2024-08-28 12:41:36,2024-08-28 11:22:21,NaT,2024-08-30 00:37:40,Yes,Excluded,2024-08-28
3,Flipkart,FWD,IN24081218523556393635ITqL86AL,IN24081218523556393635,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3305950522,2024-08-14 20:07:42,15,...,Not Available At Given Address,NaT,Undelivered,2024-08-20 17:36:09,2024-08-20 11:44:06,NaT,2024-08-27 00:28:36,Yes,Include,2024-08-20
4,Flipkart,FWD,IN24081220312236798464ITUvixX9,IN24081220312236798464,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10384193760,2024-08-14 21:21:37,15,...,Out Of Station,NaT,Undelivered,2024-08-26 14:16:26,2024-08-26 11:00:04,NaT,NaT,Yes,Include,2024-08-26

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 46 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Source                    6894 non-null   object
 1   F/R                       6894 non-null   object
 2   taskIncidentId            6894 non-null   object
 3   csIncident                6894 non-null   object
 4   Category 1                6894 non-null   object
 5   Category 2                6894 non-null   object
 6   taskStatus                6894 non-null   object
 7   task_tracking_id          6894 non-null   int64
 8   createdOn                 6894 non-null   datetime64[ns]
 9   Incident aging            6894 non-null   int64
 10  Incident aging Bucket     6894 non-null   object
 11  partnerCourierPartner     6894 non-null   object
 12  incidentPriority          6894 non-null   object
 13  vendor_collated           6894 non-null   object
 14  Status_New                6894 non-null   object
 15  Last_OFD_Date             4742 non-null   datetime64[ns]
 16  Excluded Attempts         6746 non-null   float64
 17  Open_Close                6894 non-null   object
 18  Destination_SC            6838 non-null   object
 19  Destination_Pincode       6838 non-null   float64
 20  Destination_City          6838 non-null   object
 21  Destination_State         6838 non-null   object
 22  Vendor                    6836 non-null   object
 23  Embargo Status            6894 non-null   object
 24  Report_Date               6894 non-null   object
 25  Shipper_Rad_Date          6894 non-null   object
 26  Airwaybill_No             6894 non-null   int64
 27  Pickup_Date               6778 non-null   datetime64[ns]
 28  Product_Type              6838 non-null   object
 29  Dest_DC                   6838 non-null   object
 30  Current_SC                6838 non-null   object
 31  Latest_shipment_updation  6838 non-null   datetime64[ns]
 32  Current_Status_ID         6838 non-null   float64
 33  Current_Status            6838 non-null   object
 34  Current_Status_Reason_ID  3282 non-null   float64
 35  Reason_Code               3282 non-null   object
 36  Current_Status_Reason     3282 non-null   object
 37  Bulk_Order                99 non-null     datetime64[ns]
 38  Closure_Status            6838 non-null   object
 39  latest_status_update      6838 non-null   datetime64[ns]
 40  latest_attempt            4931 non-null   datetime64[ns]
 41  RTO_Lock                  863 non-null    datetime64[ns]
 42  OFD_Lock                  283 non-null    datetime64[ns]
 43  At_DC                     6894 non-null   object
 44  Exclude_Reasons           6894 non-null   object
 45  latest_status_update1     6838 non-null   object
dtypes: datetime64[ns](9), float64(4), int64(3), object(30)
memory usage: 2.4+ MB

In [43]:
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Current_Status_Reason,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock,At_DC,Exclude_Reasons,latest_status_update1
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Address Unlocatable/Phone Not Reachable,NaT,Undelivered,2024-08-12 15:38:53,2024-08-12 12:52:02,NaT,NaT,Yes,Include,2024-08-12
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Customer Refused Delivery at Doorstep,NaT,Undelivered,2024-08-29 13:22:59,2024-08-29 10:34:13,NaT,NaT,Yes,Include,2024-08-29

In [44]:
df['latest_attempt1'] = pd.to_datetime(df['latest_attempt'],errors='coerce').dt.date
df['latest_status_update1']=df['latest_status_update1'].astype(str)

In [45]:
df.loc[df['latest_attempt'].isnull()]

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Bulk_Order,Closure_Status,latest_status_update,latest_attempt,RTO_Lock,OFD_Lock,At_DC,Exclude_Reasons,latest_status_update1,latest_attempt1
9,Flipkart,FWD,IN24081516102412233032ITFavhxQ,IN24081516102412233032ITFavhxQ,Delay in Delivery,Delay in Delivery,Customer Pain,10392132740,2024-08-15 16:10:24,14,...,NaT,Undelivered,2024-08-22 23:58:56,NaT,NaT,NaT,No,Include,2024-08-22,NaT
10,Flipkart,FWD,IN24081119364522088141ITyV391H,IN24081119364522088141,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385398031,2024-08-15 19:50:11,14,...,NaT,Undelivered,2024-08-11 08:14:33,NaT,NaT,NaT,No,Include,2024-08-11,NaT
11,Flipkart,FWD,IN24081119374082604938ITNpZWN8,IN24081119374082604938,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3306690881,2024-08-15 19:51:54,14,...,NaT,Undelivered,2024-08-11 05:33:25,NaT,NaT,NaT,Yes,Include,2024-08-11,NaT
13,Flipkart,FWD,IN24081119390788806811ITrDWKWD,IN24081119390788806811,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,3307349545,2024-08-15 20:17:05,14,...,NaT,Undelivered,2024-08-29 00:07:42,NaT,NaT,NaT,No,Include,2024-08-29,NaT
14,Flipkart,FWD,IN24081400103887247104ITxb23aF,IN24081400103887247104,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385687324,2024-08-15 20:57:40,14,...,NaT,Undelivered,2024-08-12 12:08:41,NaT,NaT,NaT,Yes,Include,2024-08-12,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,Myntra,FWD,IN24082816280962773258ITneezqO,IN24082816280962773258ITneezqO,Delayed delivery,Promise Date crossed,Open,10396353971,2024-08-29 00:00:00,0,...,NaT,Undelivered,2024-08-30 11:07:17,NaT,NaT,NaT,No,Include,2024-08-30,NaT
6872,Myntra,FWD,IN24082816450221911148IThCOgdB,IN24082816450221911148IThCOgdB,Delayed delivery,Promise Date crossed,Open,3311071503,2024-08-29 00:00:00,0,...,NaT,Undelivered,2024-08-21 18:59:02,NaT,NaT,NaT,No,Include,2024-08-21,NaT
6878,Myntra,FWD,IN24082817061100078805ITAwcF8U,IN24082817061100078805ITAwcF8U,Delayed delivery,Promise Date crossed,Open,10389454154,2024-08-29 00:00:00,0,...,NaT,Undelivered,2024-08-25 00:52:58,NaT,NaT,NaT,No,Include,2024-08-25,NaT
6879,Myntra,FWD,IN24082817072946153199ITfQoJDr,IN24082817072946153199ITfQoJDr,Delayed delivery,Promise Date crossed,Open,3310547154,2024-08-29 00:00:00,0,...,NaT,Undelivered,2024-08-22 09:10:11,NaT,NaT,NaT,Yes,Include,2024-08-22,NaT
6883,Myntra,FWD,IN24082817213202469875ITWAXH56,IN24082817213202469875ITWAXH56,Delayed delivery,Promise Date crossed,Open,3311591820,2024-08-29 00:00:00,0,...,NaT,Undelivered,2024-08-22 15:09:18,NaT,NaT,NaT,Yes,Include,2024-08-22,NaT

In [46]:
df['Current_Status'].value_counts(dropna = False)

Current_Status
DRS Closed                       1540
Undelivered                      1531
Delivered                        1168
Bag Inscan at location            633
Returned                          629
Departed From Location            607
Shipment Debagged at location     507
Bagged                             83
NaN                                56
Shipment Inscan at Location        44
Staff Out For Pickup               39
Field Pickup Done                  14
Pickup Cancelled by Ecom           13
Destroyed                          12
Field Pickup Failed                 5
Origin Facility Inscan              4
Manifested                          4
Lost                                3
Bag Added to Connection             1
Pickup Assigned to Staff            1
Name: count, dtype: int64

In [47]:
df['latest_attempt1']=df['latest_attempt1'].astype(str)

In [48]:
conditions = [
    ((df['Closure_Status'] == 'Returned') & (df['latest_status_update1']>= df['Shipper_Rad_Date'])),
    ((df['Current_Status'].isin(['DRS Closed','Delivered','DRS Created','Out for Delivery','Staff Out For Pickup','Field Pickup Done','Undelivered'])) & (df['latest_attempt1'] >= df['Shipper_Rad_Date']))
]
choices = [
    1,
    1
]

df['Outscan'] = np.select(conditions, choices, default = 0)
df['Outscan'].value_counts(dropna = False)

Outscan
0    4709
1    2185
Name: count, dtype: int64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6894 entries, 0 to 6893
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Source                    6894 non-null   object
 1   F/R                       6894 non-null   object
 2   taskIncidentId            6894 non-null   object
 3   csIncident                6894 non-null   object
 4   Category 1                6894 non-null   object
 5   Category 2                6894 non-null   object
 6   taskStatus                6894 non-null   object
 7   task_tracking_id          6894 non-null   int64
 8   createdOn                 6894 non-null   datetime64[ns]
 9   Incident aging            6894 non-null   int64
 10  Incident aging Bucket     6894 non-null   object
 11  partnerCourierPartner     6894 non-null   object
 12  incidentPriority          6894 non-null   object
 13  vendor_collated           6894 non-null   object
 14  Status_New                6894 non-null   object
 15  Last_OFD_Date             4742 non-null   datetime64[ns]
 16  Excluded Attempts         6746 non-null   float64
 17  Open_Close                6894 non-null   object
 18  Destination_SC            6838 non-null   object
 19  Destination_Pincode       6838 non-null   float64
 20  Destination_City          6838 non-null   object
 21  Destination_State         6838 non-null   object
 22  Vendor                    6836 non-null   object
 23  Embargo Status            6894 non-null   object
 24  Report_Date               6894 non-null   object
 25  Shipper_Rad_Date          6894 non-null   object
 26  Airwaybill_No             6894 non-null   int64
 27  Pickup_Date               6778 non-null   datetime64[ns]
 28  Product_Type              6838 non-null   object
 29  Dest_DC                   6838 non-null   object
 30  Current_SC                6838 non-null   object
 31  Latest_shipment_updation  6838 non-null   datetime64[ns]
 32  Current_Status_ID         6838 non-null   float64
 33  Current_Status            6838 non-null   object
 34  Current_Status_Reason_ID  3282 non-null   float64
 35  Reason_Code               3282 non-null   object
 36  Current_Status_Reason     3282 non-null   object
 37  Bulk_Order                99 non-null     datetime64[ns]
 38  Closure_Status            6838 non-null   object
 39  latest_status_update      6838 non-null   datetime64[ns]
 40  latest_attempt            4931 non-null   datetime64[ns]
 41  RTO_Lock                  863 non-null    datetime64[ns]
 42  OFD_Lock                  283 non-null    datetime64[ns]
 43  At_DC                     6894 non-null   object
 44  Exclude_Reasons           6894 non-null   object
 45  latest_status_update1     6894 non-null   object
 46  latest_attempt1           6894 non-null   object
 47  Outscan                   6894 non-null   int32
dtypes: datetime64[ns](9), float64(4), int32(1), int64(3), object(31)
memory usage: 2.5+ MB

In [50]:
df['Delivered'] = np.where( df['Current_Status']=='Delivered',1,0)
df['Delivered'].value_counts(dropna = False)

Delivered
0    5726
1    1168
Name: count, dtype: int64

In [51]:
df['Returned'] = np.where( df['Current_Status']=='Returned',1,0)
df['Returned'].value_counts(dropna = False)

Returned
0    6265
1     629
Name: count, dtype: int64

In [52]:
df['Closure'] = np.where( df['Current_Status'].isin(['Returned','Delivered']),1,0)
df['Closure'].value_counts(dropna = False)

Closure
0    5097
1    1797
Name: count, dtype: int64

In [53]:
df['Closure_Status'].value_counts(dropna = False)

Closure_Status
Undelivered    5041
Delivered      1168
Returned        629
NaN              56
Name: count, dtype: int64

In [54]:
df.shape

(6894, 51)

In [55]:
df['OFD_RTO_Status'] = np.where((~(df['OFD_Lock'].isnull()) | ~(df['RTO_Lock'].isnull())), 'OFD+RTO', 'No')
df['OFD_RTO_Status'].value_counts(dropna = False)

OFD_RTO_Status
No         5971
OFD+RTO     923
Name: count, dtype: int64

In [56]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Status_New', 'Last_OFD_Date',
       'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status', 'Report_Date', 'Shipper_Rad_Date',
       'Airwaybill_No', 'Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC',
       'Latest_shipment_updation', 'Current_Status_ID', 'Current_Status',
       'Current_Status_Reason_ID', 'Reason_Code', 'Current_Status_Reason',
       'Bulk_Order', 'Closure_Status', 'latest_status_update',
       'latest_attempt', 'RTO_Lock', 'OFD_Lock', 'At_DC', 'Exclude_Reasons',
       'latest_status_update1', 'latest_attempt1', 'Outscan', 'Delivered',
       'Returned', 'Closure', 'OFD_RTO_Status'],
      dtype='object')

In [57]:
df['Pickup_Status'] = np.where(~df['Pickup_Date'].isnull(),'Picked','NotPicked')
df['Pickup_Status'].value_counts(dropna = False)

Pickup_Status
Picked       6778
NotPicked     116
Name: count, dtype: int64

In [58]:
df["include/exclude OFD"]= np.where((~(df["OFD_Lock"].isnull()) | (df["Outscan"]==0)),'Exclude_OFD','Include_OFD')
df['include/exclude OFD'].value_counts(dropna = False)

include/exclude OFD
Exclude_OFD    4713
Include_OFD    2181
Name: count, dtype: int64

In [59]:
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Exclude_Reasons,latest_status_update1,latest_attempt1,Outscan,Delivered,Returned,Closure,OFD_RTO_Status,Pickup_Status,include/exclude OFD
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Include,2024-08-12,2024-08-12,0,0,0,0,No,Picked,Exclude_OFD
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Include,2024-08-29,2024-08-29,0,0,0,0,No,Picked,Exclude_OFD

In [60]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Status_New', 'Last_OFD_Date',
       'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status', 'Report_Date', 'Shipper_Rad_Date',
       'Airwaybill_No', 'Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC',
       'Latest_shipment_updation', 'Current_Status_ID', 'Current_Status',
       'Current_Status_Reason_ID', 'Reason_Code', 'Current_Status_Reason',
       'Bulk_Order', 'Closure_Status', 'latest_status_update',
       'latest_attempt', 'RTO_Lock', 'OFD_Lock', 'At_DC', 'Exclude_Reasons',
       'latest_status_update1', 'latest_attempt1', 'Outscan', 'Delivered',
       'Returned', 'Closure', 'OFD_RTO_Status', 'Pickup_Status',
       'include/exclude OFD'],
      dtype='object')

In [61]:
df['Outscan'].value_counts(dropna = False)

Outscan
0    4709
1    2185
Name: count, dtype: int64

In [62]:
df.columns

Index(['Source', 'F/R', 'taskIncidentId', 'csIncident', 'Category 1',
       'Category 2', 'taskStatus', 'task_tracking_id', 'createdOn',
       'Incident aging', 'Incident aging Bucket', 'partnerCourierPartner',
       'incidentPriority', 'vendor_collated', 'Status_New', 'Last_OFD_Date',
       'Excluded Attempts', 'Open_Close', 'Destination_SC',
       'Destination_Pincode', 'Destination_City', 'Destination_State',
       'Vendor', 'Embargo Status', 'Report_Date', 'Shipper_Rad_Date',
       'Airwaybill_No', 'Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC',
       'Latest_shipment_updation', 'Current_Status_ID', 'Current_Status',
       'Current_Status_Reason_ID', 'Reason_Code', 'Current_Status_Reason',
       'Bulk_Order', 'Closure_Status', 'latest_status_update',
       'latest_attempt', 'RTO_Lock', 'OFD_Lock', 'At_DC', 'Exclude_Reasons',
       'latest_status_update1', 'latest_attempt1', 'Outscan', 'Delivered',
       'Returned', 'Closure', 'OFD_RTO_Status', 'Pickup_Status',
       'include/exclude OFD'],
      dtype='object')

In [63]:
df.head(2)

,Source,F/R,taskIncidentId,csIncident,Category 1,Category 2,taskStatus,task_tracking_id,createdOn,Incident aging,...,Exclude_Reasons,latest_status_update1,latest_attempt1,Outscan,Delivered,Returned,Closure,OFD_RTO_Status,Pickup_Status,include/exclude OFD
0,Flipkart,FWD,IN24081119381919465455ITJw0gGh,IN24081119381919465455,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10385286700,2024-08-13 20:23:58,16,...,Include,2024-08-12,2024-08-12,0,0,0,0,No,Picked,Exclude_OFD
1,Flipkart,FWD,IN24081220302015151013ITgui3WN,IN24081220302015151013,Delay in Delivery,Delay in Delivery,Waiting for Internal Updates,10382037441,2024-08-14 19:53:02,15,...,Include,2024-08-29,2024-08-29,0,0,0,0,No,Picked,Exclude_OFD

In [64]:
final_df=df[['Airwaybill_No','Current_SC','Destination_SC', 'Destination_City', 'Destination_State',
       'Embargo Status', 'Pickup_Date', 'Product_Type', 'Dest_DC', 'Current_SC',
       'Latest_shipment_updation', 'Current_Status_ID', 'Current_Status',
       'Current_Status_Reason_ID', 'Reason_Code', 'Current_Status_Reason',
       'Bulk_Order', 'Closure_Status', 'latest_status_update','Report_Date', 'Shipper_Rad_Date',
       'latest_attempt', 'RTO_Lock', 'OFD_Lock', 'At_DC', 'Exclude_Reasons',
       'Outscan', 'Delivered','Returned', 'Closure', 'OFD_RTO_Status', 'Pickup_Status',
       'include/exclude OFD' ]]

In [65]:
final_df

,Airwaybill_No,Current_SC,Destination_SC,Destination_City,Destination_State,Embargo Status,Pickup_Date,Product_Type,Dest_DC,Current_SC,...,OFD_Lock,At_DC,Exclude_Reasons,Outscan,Delivered,Returned,Closure,OFD_RTO_Status,Pickup_Status,include/exclude OFD
0,10385286700,PNA,PNA,PUNE,Maharashtra,No Action,2024-08-08 07:49:14,FWD,PNA,PNA,...,NaT,Yes,Include,0,0,0,0,No,Picked,Exclude_OFD
1,10382037441,VNL,VNL,VANDALUR,Tamil Nadu,No Action,2024-08-05 03:36:19,FWD,VNL,VNL,...,NaT,Yes,Include,0,0,0,0,No,Picked,Exclude_OFD
2,10384264806,COR,COR,CHITTOR GARH,Rajasthan,No Action,2024-08-08 16:59:43,FWD,COR,COR,...,2024-08-30 00:37:40,Yes,Excluded,0,0,0,0,OFD+RTO,Picked,Exclude_OFD
3,3305950522,PPK,PPK,PUTHALAPATTU,Andhra Pradesh,No Action,2024-08-06 07:32:57,FWD,PPK,PPK,...,2024-08-27 00:28:36,Yes,Include,0,0,0,0,OFD+RTO,Picked,Exclude_OFD
4,10384193760,SXF,SXF,SRINAGAR,Jammu And Kashmir,No Action,2024-08-07 07:20:36,FWD,SXF,SXF,...,NaT,Yes,Include,0,0,0,0,No,Picked,Exclude_OFD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6889,10398779472,BRY,BRY,BAREILLY,Uttar Pradesh,No Action,2024-08-24 16:04:13,FWD,BRY,BRY,...,NaT,Yes,Include,0,1,0,1,No,Picked,Exclude_OFD
6890,3313314325,DYV,DYV,DELHI,Delhi,No Action,2024-08-27 15:37:39,FWD,DYV,DYV,...,NaT,Yes,Include,0,1,0,1,No,Picked,Exclude_OFD
6891,3313000970,ABU,ABU,ABU ROAD,Rajasthan,No Action,2024-08-25 04:11:43,FWD,ABU,ABU,...,NaT,Yes,Include,0,0,0,0,No,Picked,Exclude_OFD
6892,10396403676,MDHU,MDHU,BHIWADI,Haryana,No Action,2024-08-21 13:36:53,FWD,MDHU,MDHU,...,NaT,Yes,Include,0,0,0,0,OFD+RTO,Picked,Exclude_OFD
6893,10398378907,BTT,BTT,BALOTRA,Rajasthan,No Action,2024-08-24 02:55:53,FWD,BTT,BTT,...,NaT,Yes,Include,0,1,0,1,No,Picked,Exclude_OFD

In [66]:
d=datetime.datetime.today().strftime("%B-%d %H:%M")
d

'August-30 11:21'

In [67]:
os.chdir(r"D:\One Drive BA\OneDrive - Ecom Express Limited\Supriya_Flipkart_12247_D_0_Report")

In [68]:
pwd

'D:\\One Drive BA\\OneDrive - Ecom Express Limited\\Supriya_Flipkart_12247_D_0_Report'

In [69]:
d=datetime.datetime.today().strftime("%Y-%m-%d")
final_df.to_excel(f"D_0_RAD_12247_data_{d}.xlsx",index=False)

In [70]:
from win32com.client import Dispatch
outlook = Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.Display()

mail.To = "SUPRIYA S/IHQ/CS/CM <supriya.s@ecomexpress.in>"
#mail.To = mailing_list_to
mail.CC = "ASIM A/IHQ/BA/MGR <asim.a@ecomexpress.in>;b.gaurav@ecomexpress.in"
#mail.BCC = mailing_list_bcc
mail.Display()

mail.Subject = f'Flipkart_Daily-Escalation Closure_12247 |report_run_hour: {d}'
mail.Display()

In [71]:
html_template = """\
<!-- using this quotes for multi line commenting inbetween html -->

<!-- 
<tr> table row
<td> table data
<p> paragraph
<br> new line
-->


<html>


    <body>
        <div>  <!-- this is the very First divison created -->

            <p style = "font-family:calibri; 
                        ">
              Hi All! <br><br>              
              Please find the below link for Daily-Escalation Closure_12247|D-0 as of the captioned date.<br><br>
              <a href="https://ecomexpresssp-my.sharepoint.com/:f:/g/personal/bamis_ecomexpress_in/EnHdC99jJsNGl1UCOpHgheMBgi8ZIE373y1bwNJmVjvuPg?e=b2zJat">Esclation_12247_Report_Link</a>
              <br>
              

            </p> <!-- this is used for paragraph -->
        </div>

        <div>  <!-- this is the very Fifth divison created -->

            <p style = "font-family:calibri;">
              Note: All the views are created within the workbook with different worksheets. <br>
              

            </p> <!-- this is used for paragraph -->

        </div>


        <div>  <!-- this is the very Fifth divison created -->

            <p style = "font-family:calibri;">
              Thanks & Regards, <br>
              Team-BA<br><br>
              

            </p> <!-- this is used for paragraph -->

        </div>



    </body>
</html>


"""
          

mail.HTMLBody = html_template
mail.Display()

In [72]:
mail.send

True